remote_theme: pmarsceill/just-the-docs

title: Bakery
description: Manifest Manipulation Service

logo: /assets/images/bakery.svg

aux_links:
  "Github Repository":
    - https://github.com/cbsinteractive/bakery

exclude:
  - .gitignore
  - readme.md
