on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

name: Deploy Dev

env:
  AUTH: ${{secrets.USER_DEPLOY_REPO}}:${{secrets.PERSONAL_ACCESS_TOKEN}}
  REPO: ${{secrets.DEPLOY_REPO}}
jobs:
  deploy_dev:
    strategy:
      matrix:
        go-version: [1.13.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Configure git for private modules
        run: git config --global url."https://${AUTH}@github.com".insteadOf "https://github.com"
      - name: Don't check checksum of private repo
        run: go env -w "GONOSUMDB=github.com/cbsinteractive"
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Test
        run: go test --race -v -coverprofile=coverage.out ./...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
      - name: Deploy Dev
        run: |
          curl -XPOST -u "${AUTH}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" \
          https://api.github.com/repos/${REPO}/dispatches --data '{"event_type": "dev"}'
